project:
  type: website

website:
  title: "Quartobjspyscript"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: p1.qmd
        text: "Page 1"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



